;; Sources
(source melpa)
(source org)

;; Packages that are required by my setting.
(depends-on "org-plus-contrib")
(depends-on "toc-org" :git "https://github.com/snosov1/toc-org")
(depends-on "init-loader" :git "https://github.com/emacs-jp/init-loader")
(depends-on "molokai-theme")
(depends-on "auto-complete" :git "https://github.com/auto-complete/auto-complete")
(depends-on "haskell-mode" :git "https://github.com/haskell/haskell-mode")
(depends-on "yatex-mode" :git "https://github.com/emacsmirror/yatex")
(depends-on "yasnippet" :git "https://github.com/capitaomorte/yasnippet")
(depends-on "rinari")
  (depends-on "inf-ruby")
  (depends-on "ruby-compilation")
  (depends-on "jump")
(depends-on "rhtml" :git "https://github.com/eschulte/rhtml")
(depends-on "apples-mode" :git "https://github.com/tequilasunset/apples-mode")
(depends-on "markdown-mode" :git "https://github.com/defunkt/markdown-mode")
(depends-on "coffee-mode" :git "https://github.com/defunkt/coffee-mode")
(depends-on "scss-mode" :git "https://github.com/antonj/scss-mode")
(depends-on "websocket" :git "https://github.com/ahyatt/emacs-websocket")
(depends-on "haml-mode")
(depends-on "helm")
  (depends-on "async")
(depends-on "mew")
(depends-on "xml-rpc")
(depends-on "metaweblog")
(depends-on "org2blog")
(depends-on "minimap")
(depends-on "migemo")
